---
- name: Create network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Deploy services
  include_tasks: "../services/{{ item }}/service.yaml"
  vars:
    - name: "{{ item }}" # переменная для service.yaml
  loop: "{{ services }}"
