---
- name: Create network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Deploy services
  include_tasks: "../services/{{ item.name }}/service.yaml"
  vars:
    - name: "{{ item.name }}" # переменная для service.yaml
    - version: "{{ item.version }}"
  loop: "{{ services }}"
