---
- name: Connect to swarm
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ advertise_addr }}"
    # собираем факты о сервере 1 worker иначе manager, чтобы получить
    # токен без сохранения его локально
    join_token: >
      {{
        hostvars['server1']['ansible_facts']['token_worker']
        if type == 'worker' else
        hostvars['server1']['ansible_facts']['token_manager']
      }}
