---
rmq_defaults:
  - name: AMQP_EXCHANGE
    value: xchg_integrations
  - name: AMQP_USER
    value: "{{rmq.user}}"
  - name: AMQO_PASSWORD
    value: "{{rmq.password}}"
  - name: AMQP_HOSTNAME
    value: rmq

registry_name: "localhost:5000/"

services:
  - name: api
    version: latest
  - name: app
    version: latest
  - name: converter
    version: latest
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

# используем фильтр для rmq т.к. его не нужно билдить
non_build_services:
  - name: rmq
    version: 3-management
  - name: nginx
    version: latest

configs:
  converter:
    queue: q_imageProcessor
