---
- name: "[{{ name }}] Configure config"
  include_tasks: "../config.yaml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item

# деплоим сервис
- name: "[{{ name }}] Deploy service"
  block:
    - name: "[{{ name }}] Deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "nginx:{{ version }}"
        state: present
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 80
            target_port: 80
        configs:
          - config_name: nginx.conf
            filename: "/etc/nginx/nginx.conf"  # внутри контейнера
  tags: "{{ name }}"
