---
- name: Init a new swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Directory exist
  delegate_to: localhost
  file:
    path: ./tokens
    state: directory
    mode: '0664'


# сохраняем токены локально из сворма на хост
- name: Save token 'manager'
  delegate_to: localhost
  copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    mode: '0664'

- name: Save token 'worker'
  delegate_to: localhost
  copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    mode: '0664'
