---
- name: "[{{ name }}] Create config"
  # подставляем в name имя сервиса из main.yaml
  vars:
    config_file: "{{ lookup('template', '{{ name }}/{{ config_item }}.j2') }}"
  community.docker.docker_config:
    name: "{{ config_item }}"
    data: "{{ config_file | b64encode }}"
    # если поменялся контент файла .env то и поменялся хэш и label
    labels:
      config: "{{ config_file | hash('sha1') }}"
    data_is_b64: true
    state: present
