---
- name: "[{{ name }}] Configure secret"
  # подставляем в name имя сервиса из main.yaml
  vars:
    env_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ env_file | b64encode }}"
    # если поменялся контент файла .env то и поменялся хэш и label
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present
