---
- name: "[{{ name }}] Configure secret"
  block:
    - name: "[{{ name }}] Create secret"
      include_tasks: "secret-create.yaml"
  tags: "{{ name }}"

  # в случае ошибки перехватываем rescue и удаляем сервис с секретом
  rescue:
    - name: "[{{ name }}] Delete service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

  # снова созадем секрет
    - name: "[{{ name }}] Create secret"
      include_tasks: "secret-create.yaml"
